### ISSUE TITLE
Issue with playing levels

### ISSUE THREAD

**Issue by werlucad** [mateoconlechuga/oiram-editor#2]
I have downloaded the oiram editor and used it, i make a level put in a name, description, and author, and then press save. I saves the file, and then using ce connect i put it on my calculator. But when i launch Oiram, the level is gone and doesn's show up in oiram but still in the file view.

**Comment by clippycoder** [comment]
It might be the program itself that's the problem.

**Comment by werlucad** [comment]
Do you have any ideas on where to find the functioning software or how to fix what it is doing

**Comment by mateoconlechuga** [comment]
You should download the latest Oiram from here: https://www.cemetech.net/programs/index.php?mode=file&path=/84pce/asm/games/oiram.zip
