### ISSUE TITLE
Building Custom Editor

### ISSUE THREAD

**Issue by DT-is-not-available** [mateoconlechuga/oiram-editor#4]
Hey, so I have gotten into modding oiram and adding new things, and was wondering how I could build my own version of the level editor for oiram? There is a source code download but how do I either run it/compile it for testing?

**Comment by adriweb** [comment]
You have to install the open-source Qt SDK: https://www.qt.io/download-qt-installer
Then in Qt Creator, setup your toolchain etc. (Kit) then open `OiramLevelEditor.pro`, then build & run it.

**Comment by DT-is-not-available** [comment]
ok thanks! I will try that

**Comment by DT-is-not-available** [comment]
how do i set it up to compile it, as this is my first time using the software?

**Comment by adriweb** [comment]
You should follow standard Qt-related tutorials, there isn't anything specific here.

**Comment by DT-is-not-available** [comment]
Yes but what kit should i be using for oiram/how do i make the kit i should be using for oiram?

**Comment by adriweb** [comment]
That's not a question related to this project, please just look at Qt tutorials for that.
