### ISSUE TITLE
ORIAM Editor Crashing when opening a certain pack and another question

### ISSUE THREAD

**Issue by ghost** [mateoconlechuga/oiram-editor#5]
When I try to open a certain pack I made in ORIAM Editor, the app crashes. This happened after I added level four to this pack. However, when I open a different test pack I also made, the editor works and allows me to edit it just fine. And now when I get to level 4 on my calculator this is what it looks like. My level isn't supposed to look like this and those weren't even blocks I've used. I also die right away when I play that level.

[BLsOIRAM.zip](https://github.com/mateoconlechuga/oiram-editor/files/5387461/BLsOIRAM.zip)
![Level 4](https://user-images.githubusercontent.com/65474198/96181561-75ba8f80-0ef1-11eb-951a-4fd7eafb85fb.jpg)

I have another question too; How can I zoom in in the editor so everything isn't so small so it's easier to work with?

**Comment by eschan145** [comment]
I have the same problem.
