### ISSUE TITLE
doesnt work for Mac

### ISSUE THREAD

**Issue by Electricgd** [mateoconlechuga/oiram-editor#6]
doesnt work for mac, it says my mac cant run windows applications :(

**Comment by adriweb** [comment]
I can build a mac version but I guess @mateoconlechuga needs to do a new release for the last commit anyway :P

**Comment by mateoconlechuga** [comment]
I'll add cmake in there and see what happens

**Comment by Electricgd** [comment]
👍

**Comment by Electricgd** [comment]
how long do you think it will take?

**Comment by mateoconlechuga** [comment]
It is now building in CI, if @adriweb wants to take a look into how to properly package for mac

**Comment by adriweb** [comment]
Hm well I wouldn't be able to provide codesigned+notarized builds in this CI, but I suppose you can make it upload artifacts at least, and I'll just sign things manually

**Comment by mateoconlechuga** [comment]
@adriweb Here's the run (only releasing qt6):

https://github.com/mateoconlechuga/oiram-editor/actions/runs/11575018982

And the release draft:

https://github.com/mateoconlechuga/oiram-editor/releases/tag/untagged-04ebc7aaa4094b12d33e

**Comment by Electricgd** [comment]
not quite sure how to download it? im looking everywhere and i cant find a good release for the mac

**Comment by mateoconlechuga** [comment]
I'm still waiting for @adriweb to sign it, just letting him know where he can find it. It'll be released once he does that.

**Comment by adriweb** [comment]
Yeah, about to take care of that now

**Comment by adriweb** [comment]
Alright, I gave @mateoconlechuga the signed binary to upload (it's in a dmg file).

I'm not too sure about the additional notarization stuff since I haven't done that manually in forever. If it complains when you try to open `oiram-editor`, you can open System settings > Security > scroll down a bit and click "Open anyway" or something, and try again.

**Comment by mateoconlechuga** [comment]
@Electricgd Download is here: https://github.com/mateoconlechuga/oiram-editor/releases/tag/v1.7

Let me know if you have any issues or have to do anything special, should just be a straightforward DMG though

**Comment by mateoconlechuga** [comment]
It looks like there might be some signing issues, so maybe just wait a little bit then I can update the download

**Comment by adriweb** [comment]
well, try and let us know I guess. We won't be able to immediately fix it (although I'll be able to provide a fixed arm build I guess)

**Comment by adriweb** [comment]
An ARM build that's confirmed to work without any issues is also available soon whenever Mateo can upload it :)
We'll fix the intel build later.

**Comment by Electricgd** [comment]
thank you so much guys!!!On Oct 29, 2024, at 5:43 PM, Adrien Bertrand ***@***.***> wrote:﻿
An ARM build that's confirmed to work without any issues is also available soon whenever Mateo can upload it :)
We'll fix the intel build later.

**Comment by mateoconlechuga** [comment]
https://github.com/mateoconlechuga/oiram-editor/releases/latest

Uploaded and available here - the macOS app icon is a little low-res, but everything should work

**Comment by mateoconlechuga** [comment]
@Electricgd would you mind trying the lastet release (v1.8) here? https://github.com/mateoconlechuga/oiram-editor/releases/tag/v1.8

Just want to see if the universal app works, and that the program icon resolution looks a little better

**Comment by Electricgd** [comment]
could you guys make custom geometry dash ce levels? 2 levels isnt enough and lots of people want more levels

**Comment by mateoconlechuga** [comment]
This is not the appropriate place to ask this. However, levels can be found here: https://tiplanet.org/forum/archives_list.php?cat=Jeux+Levels+Geometry+Dash+ce

**Comment by Electricgd** [comment]
got it, thanks!
